config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for    :users, :controllers => {
 :registrations => 'users/registrations'
  }
  root          'items#index'
  resources :users do
    member do
      get  'shooting'

      post 'shooting_end'
    end
  end

  resources :items do
    member do
      get  'buy'
      post 'buy_finish'
    end
  end
  resources :trades
  resources :my_pages do
    collection do
      get 'sell_list'
      get 'buy_list'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many     :items
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :shooting, :shooting_end]
  def edit
  end

  def update
    @user.update(user_params)
    redirect_to root_path
  end

  def show
  end

  def shooting
  end

  def shooting_end
    @user.update(clear: 1)
    redirect_to root_path
  end

  private
   def user_params
    params.require(:user).permit(:nickname, :family_name, :name, :family_name_kana, :name_kana, :postal_code, :prefecture, :city, :town, :building_name, :phone_number, :card_number, :expiration_number, :security_code)
   end

   def set_user
     @user = User.find(params[:id])
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.container
  %registration_header
    = render partial: "layouts/header_plane"
  .main
    .form
      .form__title 会員情報変更
      .form__body
        = form_for(@user) do |f|
          .form__field
            = f.label "ニックネーム", class: "form__field__label"
            %br
            = f.text_field :nickname, value: current_user.nickname, class: "form__field__form"
          .form__field
            = f.label "メールアドレス", class: "form__field__label"
            %br
            = f.email_field :email, autofocus: true, value: current_user.email, class: "form__field__form"
          .form__field
            = f.label "新パスワード", class: "form__field__label"
            %br
            = f.password_field :password, autocomplete: "off", place_holder: "パスワードを更新しない場合は空欄にしてください。", class: "form__field__form"

          .form__field
            = f.label "新パスワード（確認）", class: "form__field__label"
            %br
            = f.password_field :password_confirmation, autocomplete: "off", place_holder: "パスワードを更新しない場合は空欄にしてください。", class: "form__field__form"
          .form__field
            = f.label "現在のパスワード", class: "form__field__label"
            %br
            = f.password_field :current_password, autocomplete: "off", place_holder: "現在のパスワードを入力してください。", class: "form__field__form"

          .form__field
            = f.label "お名前", class: "form__field__label"
            %br
            = f.text_field :family_name, value: current_user.family_name, class: "form__field__form"
            %br
            = f.text_field :name, value: current_user.name, class: "form__field__form"

          .form__field
            = f.label "お名前 カナ", class: "form__field__label"
            %br
            = f.text_field :family_name_kana, value: current_user.family_name_kana, class: "form__field__form"
            %br
            = f.text_field :name_kana, value: current_user.name_kana, class: "form__field__form"

          .form__field
            = f.label "郵便番号", class: "form__field__label"
            %br
            = f.text_field :postal_code, value: current_user.postal_code, class: "form__field__form"

          .form__field
            = f.label "都道府県", class: "form__field__label"
            %br
              = f.text_field :prefecture, class: "form__field__form", selected: current_user.prefecture

          .form__field
            = f.label "市町村区", class: "form__field__label"
            %br
            = f.text_field :city, value: current_user.city, class: "form__field__form"

          .form__field
            = f.label "町名", class: "form__field__label"
            %br
            = f.text_field :town, value: current_user.town, class: "form__field__form"

          .form__field
            = f.label "建物名", class: "form__field__label"
            %br
            = f.text_field :building_name, value: current_user.building_name, class: "form__field__form"

          .form__field
            = f.label "電話番号", class: "form__field__label"
            %br
            = f.text_field :phone_number, value: current_user.phone_number, class: "form__field__form"

          .form__field
            = f.submit "更新", class: "form__field__button"
          .form__field
            = link_to "戻る", root_path, class: "form__field__button form__field__button--grey"

  = render partial: "layouts/registration_footer"

app/views/users/shooting.html.haml
.shooting.hidden
  = link_to "HOMEボタン", shooting_end_user_path(@user), method: :post, class: "shooting__btn"
= javascript_include_tag "engine.js"
= javascript_include_tag "danmaku.js"


/ = link_to "購入する", buy_finish_item_path(@item), method: :post,class: "item_info__buy_btn"

app/views/users/show.html.haml
.container
  = render partial: "layouts/header"
  .container__inner.clearfix
    .container__inner__list_box.container__right_inner
      .container__inner__list_box__title.container__right_inner__user_box
        .container__right_inner__user_box__name_box
          .container__right_inner__user_box__name_box__name
            %h2 #{@user.name} さん
        .container__right_inner__user_box__follow_box
          - unless @follower
            .follow_btn#follow{ data: {user_id: current_user.id, followed_user_id: @user.id} }フォローする
          - else
            .follow_btn.follow_btn--stop#stop_follow{ data: {follower_id: @follower.id, user_id: current_user.id, followed_user_id: @user.id } } フォロー中
      = render partial: "layouts/small_item_list", locals: {title: "この出品者の商品"}
  = render partial: "layouts/footer"