config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for    :users, :controllers => {
 :registrations => 'users/registrations'
  }
  root          'items#index'
  resources :users do
    member do
      get  'shooting'

      post 'shooting_end'
    end
  end

  resources :items do
    member do
      get  'buy'
      post 'buy_finish'
    end
  end
  resources :trades
  resources :my_pages do
    collection do
      get 'sell_list'
      get 'buy_list'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to    :user
  has_one       :trade
  has_many      :comments
  has_many      :item_images

  accepts_nested_attributes_for :trade
  accepts_nested_attributes_for :item_images,
                                :allow_destroy => true
                                # :reject_if     => :reject_item_image

  def reject_item_image(attributed)
    attributed['item_images'].blank?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :buy, :buy_finish]
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @item.build_trade
     4.times{ @item.item_images.build }
  end

  def create
    @item = Item.create(item_params)
    redirect_to root_path
  end

  def edit
    num = 4 - @item.item_images.count
    unless num == 0
      num.times{ @item.item_images.build }
    end
  end

  def show
    @user = User.find(@item.user_id)
  end

  def update
    @item.update(item_edit_params)
    redirect_to root_path
  end

  def buy
  end

  def buy_finish
    @item.update(buy: 1)
  end

  private

    def item_params
      param = params.require(:item).permit(:name, :body, :price, :category, :state, item_images_attributes: [:image], trade_attributes: [:trade_type, :days, :fee_type, :area]).merge(user_id: current_user.id, evaluate_price: 0)
      param["item_images_attributes"].delete_if{ |a| a == nil }
      return param
    end

    def item_edit_params
      params.require(:item).permit(:name, :body, :price, :category, :state, item_attributes: [:item_id], item_images_attributes: [:image], trade_attributes: [:trade_type, :days, :fee_type, :area, :item_id, :id]).merge(user_id: current_user.id, evaluate_price: 0)
    end

    def set_item
      @item = Item.find(params[:id])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/buy.html.haml
.container
  = render partial: "layouts/header_plane"
  .main
    .form
      .form__inner
        %p.form__title 購入を確定しますか？
      .form__inner
        .form__inner__container
          .item_info
            = image_tag @item.item_images[0].image, class: "item_info__item_image"
            %p.item_info__item_name #{@item.name}
            .item_info__price_info
              %p.item_info__price_info__item_price ¥ #{@item.price}
              %p.item_info__price_info__delivery_fee #{@item.trade.days}
            .item_info__total_info.clearfix
              %p.item_info__total_info__title 支払い金額
              %p.item_info__total_info__price ¥ #{@item.price}
            = link_to "購入する", buy_finish_item_path(@item), method: :post,class: "item_info__buy_btn"
      .form__inner
        .form__inner__container
          %p.buy_info__title 配送先
          .address_info
            %ul.address_info__list.buy_info__list
              %li.address_info__zip_code 〒#{current_user.postal_code}
              %li.address_info__address  #{current_user.prefecture}#{current_user.city}#{current_user.town}#{current_user.building_name}
              %li.address_info__name     #{current_user.family_name} #{current_user.name}
  = render partial: "layouts/registration_footer"

app/views/items/buy_finish.html.haml
.container
  = render partial: "layouts/header_plane"
  .main
    .form
      .form__inner
        %p.form__title 購入が完了しました。
      .form__inner
        .form__inner__container
          .item_info
            = image_tag @item.item_images[0].image, class: "item_info__item_image"
            %p.item_info__item_name #{@item.name}
            .item_info__price_info
              %p.item_info__price_info__item_price ¥#{@item.price}
              %p.item_info__price_info__delivery_fee #{@item.trade.trade_type}
      .form__inner
        .form__inner__container
          %p.buy_info__title 配送先
          .address_info
            %ul.address_info__list.buy_info__list
              %li.address_info__zip_code 〒#{current_user.postal_code}
              %li.address_info__address  #{current_user.prefecture}#{current_user.city}#{current_user.town}#{current_user.building_name}
              %li.address_info__name     #{current_user.family_name} #{current_user.name}

      .form__inner
        .form__inner__container
          .transaction_info
            %p.buy_info__title 発送通知後の流れ
            %ul.transaction_info__list.buy_info__list
              %li.transaction_info__list__item
                %span.evaluation_icon.icon_face--good
                  %i.icon.fa.fa-circle.fa-stack-1x.color_good
                  %i.icon.fa.fa-smile-o.fa-stack-1x.fa-inverse
                %span.evaluation_icon.icon_face--normal
                  %i.icon.fa.fa-circle.fa-stack-1x.color_normal
                  %i.icon.fa.fa-meh-o.fa-stack-1x.fa-inverse
                %span.evaluation_icon.icon_face--bad
                  %i.icon.fa.fa-circle.fa-stack-1x.color_bad
                  %i.icon.fa.fa-frown-o.fa-stack-1x.fa-inverse
              %li.transaction_info__list__item
                %p.transaction_description
                  商品を受け取ったら
                  %br/
                  出品者の評価をしましょう。
                  %br/
                  購入代金が出品者に振り込まれます。
                  %br/
                  評価後に取引は完了です。
              %li.transaction_info__list__item
                = link_to "トップページへもどる", root_path
  = render partial: "layouts/registration_footer"

app/views/items/edit.html.haml
.container
  = render partial: "layouts/header_plane"
  .main
    .form
      =form_for @item, :url => { controller => "my_pages", :action => "update" } do |f|
        .sell_form__inner
          %p.form__title 商品の情報入力
        .sell_form__inner
          .sell_form__inner__container
            %i.form__field__must_info 必須
            %p.sell_form__supplement 最大4枚までアップロードできます。

            .sell_form__drop_box
              %p.sell_form__drop_box__supplement_edit クリックしてファイルをアップロード
            = f.fields_for :item_images do |pf|
              = pf.file_field :image, class: 'item_images'

        .sell_form__inner
          .sell_form__inner__container
            .sell_form__inner__container__sub_container
              %p.sell_form__label 商品名
              =f.label "商品名", class: "sell_form__label"
              %i.form__field__must_info 必須
              = f.text_field :name, placeholder: "商品名（必須 40文字まで）", class: "sell_form__input"

            .sell_form__inner__container__sub_container
              %p.sell_form__label 商品の説明
              =f.label "商品説明", class: "sell_form__label"
              %i.form__field__must_info 必須
              = f.text_area :body, placeholder: "商品名（必須 商品の説明）", class: "sell_form__input sell_form__item_description"
        .sell_form__inner
          .sell_form__inner__container.clearfix
            %p.sell_form__info_head 商品の詳細
            .sell_form__inner__container--right
              .sell_form__inner__container__sub_container
                %p.sell_form__label カテゴリー
                %i.form__field__must_info 必須
                =f.select :category, [["---", "---"], ["レディース", "レディース"], ["メンズ", "メンズ"], ["ベビー・キッズ", "ベビー・キッズ"], ["インテリア・住まい・小物", "インテリア・住まい・小物"], ["エンタメ・ホビー", "エンタメ・ホビー"], ["コスメ・香水・美容", "コスメ・香水・美容"], ["家電・スマホ・カメラ", "家電・スマホ・カメラ"], ["スポーツ・レンジャー", "スポーツ・レンジャー"], ["ハンドメイド", "ハンドメイド"], ["チケット", "チケット"], ["自転車・オートバイ", "オートバイ"], ["その他", "その他"]]
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 商品の状態
                %i.form__field__must_info 必須
                =f.select :state, [["---", "---"], ["新品・未使用", "新品・未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れはなし", "目立った傷や汚れはなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]] ,{class: "sell_form__price_form"}

        .sell_form__inner
        = f.fields_for :trade do |pp|
          .sell_form__inner__container.clearfix
            %p.sell_form__info_head 配送について
            .sell_form__inner__container--right
              .sell_form__inner__container__sub_container
                %p.sell_form__label 配送量の負担
                %i.form__field__must_info 必須
                =pp.select :fee_type, [["---", "---"], ["送料込み(出品者負担)", "送料込み(出品者負担)"], ["着払い", "着払い"]], { class: "sell_form__input sell_form__input--select" }
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 配送の方法
                %i.form__field__must_info 必須
                =pp.select :trade_type, [["---", "---"], ["未定", "未定"], ["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"], ["レターパック", "レターパック"], ["普通郵便(定型・定形外)", "普通郵便(定型・定形外)"], ["クロネコヤマト", "クロネコヤマト"], ["ゆうパック", "ゆうパック"], ["ポスパケット・ゆうパケット", "ポスパケット・ゆうパケット"]] ,{class: "sell_form__input sell_form__input--select"}
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 発送元の地域
                %i.form__field__must_info 必須
                =pp.collection_select :area, JpPrefecture::Prefecture.all, :name, :name, {class: "sell_form__input sell_form__input--select"}
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 発送までの日数
                %i.form__field__must_info 必須
                =pp.select :days, [["---", "---"], ["1〜2日で配送", "1〜2日で配送"], ["2〜3日で配送", "2〜3日で配送"], ["4〜7日で配送", "4〜7日で配送"]] ,{class: "sell_form__input sell_form__input--select"}
                = pp.hidden_field :item_id, value: @item.id

        .sell_form__inner
          .sell_form__inner__container.clearfix
            %p.sell_form__info_head 販売価格(300〜9,999,999)
            .sell_form__inner__container--right
              .sell_form__inner__container--for_price_form.clearfix
                %p.sell_form__label 価格
                %i.form__field__must_info 必須
                = f.text_field :price, placeholder: "例）3000", class: "sell_form__price_form", id: "input_price"
              .sell_form__inner__container__price_sub_container.clearfix.fs14
                %p.sell_form__inner__container__price_sub_container__head 販売手数料(10%)
                .sell_form__inner__container__price_sub_container__info#commission_box -
              .sell_form__inner__container__price_sub_container.clearfix.fs16.bold
                %p.sell_form__inner__container__price_sub_container__head 販売利益
                .sell_form__inner__container__price_sub_container__info#profit_box -

        .sell_form__inner
          .sell_form__inner__container
            %p.sell_form__notice
              禁止されている出品、行為を必ずご確認ください。
              %br/
              またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            .sell_form__inner__container__sub_container--has_margin
              = f.submit "編集する", class: "form__btn form__btn--red"
              = link_to "もどる", root_path, class: "form__btn form__btn--grey form__btn--small"

  = render partial: "layouts/registration_footer"

app/views/items/index.html.haml
.container
  = render partial: "layouts/header"

  .front_image#front_image
    .front_image__conamibutton.hidden
      -if user_signed_in?
        =link_to 'push', shooting_user_path(current_user)

    .front_image__left_box.front_image_item
      %h1
        スマホでかんたん
        %br/
        フリマアプリ
      %p
        コピカリはスマホカメラからすぐに出品できる
        %br/
        購入時も安心な独自システムのアプリのダミーです。

      .front_image__left_box__stores.front_image_item.clearfix
        = image_tag "app-store.svg", class: "front_image__left_box__stores__image"
        = image_tag "google-play.svg", class: "front_image__left_box__stores__image front_image__left_box__stores__image--right"
    = image_tag "front_image.png", class: "front_image__phone_image front_image_item"
    #front_image_inner_bottom

  .consept_section
    %h2.concept_section__text
      コピカリは、かんたんに売り買いができて、
      %br/
      あんしん・あんぜんなお取引ができる
      %br/
      フリマアプリっぽいサイトです。
    .top_introduce
      .top_introduce__box
        .top_introduce__box__title
        %span.top_introduce__box__title__number 1
        %span.top_introduce__box__title__character 簡単に出品できる
        .top_introduce__box__image
        = image_tag "sell_image.jpg", class: "top_introduce__box__image__img"
        .top_introduce__box__introduce
          スマホで写真を撮って
          %br/
          特徴を入力するだけで、
          %br/
          簡単に出品できます。
      .top_introduce__box
        .top_introduce__box__title
        %span.top_introduce__box__title__number 2
        %span.top_introduce__box__title__character すぐに購入できる
        .top_introduce__box__image
        = image_tag "merucari_sample.jpg", class: "top_introduce__box__image__img"
        .top_introduce__box__introduce
          ボタン1つで即購入。
          %br/
          あとは出品者からの発送を
          %br/
          待つだけです。
      .top_introduce__box
        .top_introduce__box__title
        %span.top_introduce__box__title__number 3
        %span.top_introduce__box__title__character 商品がたくさん
        .top_introduce__box__image
        = image_tag "merucari_many.jpg", class: "top_introduce__box__image__img"
        .top_introduce__box__introduce
          毎日数十万品以上の新商
          %br/
          品が
          %br/
          出品されるので、ほしい
          %br/
          ものがきっと見つかりま
          %br/
          す。

  .front_image2#front_image
    .front_image__left_box.front_image_item
      .front_image__left_box
      誰でも簡単に、売ったり買ったりを楽しめる
      %p
        メルカリには、
        %br/
        ファッションから雑貨、家電、本や漫画に至るまで、
        %br/
        幅広いジャンルの商品がたくさん。
        %br/
        今がもう店頭に置いていない掘り出し物も見つかるかもしれません。
        %br/
        早速アプリをダウンロードして始めよう！

      .front_image__left_box__stores.front_image_item.clearfix
        = image_tag "app-store.svg", class: "front_image__left_box__stores__image"
        = image_tag "google-play.svg", class: "front_image__left_box__stores__image front_image__left_box__stores__image--right"




  .items_container.clearfix
    %h2.section_title 新着アイテム
    %i.fa.fa-camera
    %h3.category_name カテゴリー

    = render partial: "layouts/items_list"
  .front_image3#front_image
    .front_image__left_box.front_image_item
      .front_image__left_box
      スマホでかんたんフリマアプリ
      %br/
      今すぐダウンロード！！

      .front_image__left_box__stores.front_image_item.clearfix
        = image_tag "app-store.svg", class: "front_image__left_box__stores__image"
        = image_tag "google-play.svg", class: "front_image__left_box__stores__image front_image__left_box__stores__image--right"
        = image_tag "hand.png", class: "front_image__phone_image2"

  = render partial: "layouts/footer"

app/views/items/new.html.haml
.container
  = render partial: "layouts/header_plane"
  .main
    .form
      =form_for(@item) do |f|
        .sell_form__inner
          %p.form__title 商品の情報入力
        .sell_form__inner
          .sell_form__inner__container
            %i.form__field__must_info 必須
            %p.sell_form__supplement 最大4枚までアップロードできます。

            .sell_form__drop_box
            %p.sell_form__drop_box__supplement クリックしてファイルをアップロード
            = f.fields_for :item_images do |pf|
              = pf.file_field :image, class: 'item_images'

        .sell_form__inner
          .sell_form__inner__container
            .sell_form__inner__container__sub_container
              %p.sell_form__label 商品名
              =f.label "商品名", class: "sell_form__label"
              %i.form__field__must_info 必須
              = f.text_field :name, placeholder: "商品名（必須 40文字まで）", class: "sell_form__input"

            .sell_form__inner__container__sub_container
              %p.sell_form__label 商品の説明
              =f.label "商品説明", class: "sell_form__label"
              %i.form__field__must_info 必須
              = f.text_area :body, placeholder: "商品名（必須 商品の説明）", class: "sell_form__input sell_form__item_description"

        .sell_form__inner
          .sell_form__inner__container.clearfix
            %p.sell_form__info_head 商品の詳細
            .sell_form__inner__container--right
              .sell_form__inner__container__sub_container
                %p.sell_form__label カテゴリー
                %i.form__field__must_info 必須
                =f.select :category, [["---", "---"], ["レディース", "レディース"], ["メンズ", "メンズ"], ["ベビー・キッズ", "ベビー・キッズ"], ["インテリア・住まい・小物", "インテリア・住まい・小物"], ["エンタメ・ホビー", "エンタメ・ホビー"], ["コスメ・香水・美容", "コスメ・香水・美容"], ["家電・スマホ・カメラ", "家電・スマホ・カメラ"], ["スポーツ・レンジャー", "スポーツ・レンジャー"], ["ハンドメイド", "ハンドメイド"], ["チケット", "チケット"], ["自転車・オートバイ", "オートバイ"], ["その他", "その他"]]
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 商品の状態
                %i.form__field__must_info 必須
                =f.select :state, [["---", "---"], ["新品・未使用", "新品・未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れはなし", "目立った傷や汚れはなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]] ,{class: "sell_form__price_form"}

        .sell_form__inner
        = f.fields_for :trade do |pp|
          .sell_form__inner__container.clearfix
            %p.sell_form__info_head 配送について
            .sell_form__inner__container--right
              .sell_form__inner__container__sub_container
                %p.sell_form__label 配送量の負担
                %i.form__field__must_info 必須
                =pp.select :fee_type, [["---", "---"], ["送料込み(出品者負担)", "送料込み(出品者負担)"], ["着払い", "着払い"]]
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 配送の方法
                %i.form__field__must_info 必須
                =pp.select :trade_type, [["---", "---"], ["未定", "未定"], ["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"], ["レターパック", "レターパック"], ["普通郵便(定型・定形外)", "普通郵便(定型・定形外)"], ["クロネコヤマト", "クロネコヤマト"], ["ゆうパック", "ゆうパック"], ["ポスパケット・ゆうパケット", "ポスパケット・ゆうパケット"]] ,{class: "sell_form__price_form"}
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 発送元の地域
                %i.form__field__must_info 必須
                =pp.collection_select :area, JpPrefecture::Prefecture.all, :name, :name, {class: "sell_form__input sell_form__input--select"}
              .sell_form__inner__container__sub_container--has_margin
                %p.sell_form__label 発送までの日数
                %i.form__field__must_info 必須
                =pp.select :days, [["---", "---"], ["1〜2日で配送", "1〜2日で配送"], ["2〜3日で配送", "2〜3日で配送"], ["4〜7日で配送", "4〜7日で配送"]] ,{class: "sell_form__input sell_form__input--select"}
                = pp.hidden_field :item_id, value: @item.id

        .sell_form__inner
          .sell_form__inner__container.clearfix
            %p.sell_form__info_head 販売価格(300〜9,999,999)
            .sell_form__inner__container--right
              .sell_form__inner__container--for_price_form.clearfix
                %p.sell_form__label 価格
                %i.form__field__must_info 必須
                = f.text_field :price, placeholder: "例）3000", class: "sell_form__price_form", id: "input_price"
              .sell_form__inner__container__price_sub_container.clearfix.fs14
                %p.sell_form__inner__container__price_sub_container__head 販売手数料(10%)
                .sell_form__inner__container__price_sub_container__info#commission_box -
              .sell_form__inner__container__price_sub_container.clearfix.fs16.bold
                %p.sell_form__inner__container__price_sub_container__head 販売利益
                .sell_form__inner__container__price_sub_container__info#profit_box -

        .sell_form__inner
          .sell_form__inner__container
            %p.sell_form__notice
              禁止されている出品、行為を必ずご確認ください。
              %br/
              またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            .sell_form__inner__container__sub_container--has_margin
              = f.submit "出品する", class: "form__btn form__btn--red"
              = link_to "もどる", root_path, class: "form__btn form__btn--grey form__btn--small"

  = render partial: "layouts/registration_footer"

app/views/items/search.html.haml
.container
  = render partial: "layouts/header"
  .items_container
    %h2.section_title 検索結果
    %h3.category_name 『#{@keyword}』を含む商品一覧
    = render partial: "layouts/items_list"
  = render partial: "layouts/footer"

app/views/items/show.html.haml
.container
  = render partial: "layouts/header"
  =form_for(@item) do |f|
    .item_container
      %h2.item__title #{@item.name}
      .item__data_box.clearfix
        .item__image_box
          .item__image_box__upper
            = image_tag @item.item_images[0].image, class: "item__image_box__upper__image"
          .item__image_box__bottom
            - if @item.item_images[0].image.present?
              = image_tag @item.item_images[0].image, class: "item__image_box__bottom__image item__image_box__bottom__image--over item_thumbnails", id: "item_image_id"
            - else
              = image_tag "logos/copicari_logo_small.png", class: "item__image_box__bottom__image"
            - (1..3).each do |num|
              - if @item.item_images[num].present?
                = image_tag @item.item_images[num].image, class: "item__image_box__bottom__image item_thumbnails", id: "item_image_box_id"
              - else
                = image_tag "logos/copicari_logo_small.png", class: "item__image_box__bottom__image", id: "item_image__bottom_id"
        %table.item__data_table
          %tr
            %th 出品者
            %td #{@item.user.family_name} #{@item.user.name}
          %tr
            %th カテゴリー
            %td #{@item.category}
          %tr
            %th 商品の状態
            %td #{@item.state}
          %tr
            %th 配送料の負担
            %td #{@item.trade.fee_type}
          %tr
            %th 配送の方法
            %td #{@item.trade.trade_type}
          %tr
            %th 配送元地域
            %td #{@item.trade.area}
          %tr
            %th 配送日の目安
            %td #{@item.trade.days}
      .item__price__box
        .item__description= simple_format br @item.body
        .item__price__sub
          .item__price__price__head
          .item__price__price__center
            .item__price__price
              = @item.price
              %span  円
              / =f.select :evaluate_price, [["---", "---"], [1, 1], [10, 10], [100, 10], [500, 500], [1000, 1000], [5000, 5000], [10000, 10000]] ,{class: "sell_form__input sell_form__input--select"}
          .item__price__price__bottom
            .item__price__tax   (税 ¥0)
            .item__price__delivery_fee 送料込み

        - if user_signed_in? && @user.id == current_user.id
          = link_to "編集", edit_item_path , class: "item__purchase_btn"
        - elsif user_signed_in?
          = link_to "購入", buy_item_path(@item.id), class: "item__purchase_btn"
        - else

    / .item_comment
    /   .item_comment__box
    /   .item_comment__attention
    /   aiueo

    /   = link_to "コメントする", edit_item_path , class: "item__purchase_btn"

  = render partial: "layouts/footer"