config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for    :users, :controllers => {
 :registrations => 'users/registrations'
  }
  root          'items#index'
  resources :users do
    member do
      get  'shooting'

      post 'shooting_end'
    end
  end

  resources :items do
    member do
      get  'buy'
      post 'buy_finish'
    end
  end
  resources :trades
  resources :my_pages do
    collection do
      get 'sell_list'
      get 'buy_list'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to    :user
  has_one       :trade
  has_many      :comments
  has_many      :item_images

  accepts_nested_attributes_for :trade
  accepts_nested_attributes_for :item_images,
                                :allow_destroy => true
                                # :reject_if     => :reject_item_image

  def reject_item_image(attributed)
    attributed['item_images'].blank?
  end
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :image, ImageUploader
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :item, optional: true
  # belongs_to :user
  # accepts_nested_attributes_for :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many     :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name_kana])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name_kana])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:prefecture])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:city])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:town])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:building_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:card_number])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:expiration_number])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:security_code])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :buy, :buy_finish]
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @item.build_trade
     4.times{ @item.item_images.build }
  end

  def create
    @item = Item.create(item_params)
    redirect_to root_path
  end

  def edit
    num = 4 - @item.item_images.count
    unless num == 0
      num.times{ @item.item_images.build }
    end
  end

  def show
    @user = User.find(@item.user_id)
  end

  def update
    @item.update(item_edit_params)
    redirect_to root_path
  end

  def buy
  end

  def buy_finish
    @item.update(buy: 1)
  end

  private

    def item_params
      param = params.require(:item).permit(:name, :body, :price, :category, :state, item_images_attributes: [:image], trade_attributes: [:trade_type, :days, :fee_type, :area]).merge(user_id: current_user.id, evaluate_price: 0)
      param["item_images_attributes"].delete_if{ |a| a == nil }
      return param
    end

    def item_edit_params
      params.require(:item).permit(:name, :body, :price, :category, :state, item_attributes: [:item_id], item_images_attributes: [:image], trade_attributes: [:trade_type, :days, :fee_type, :area, :item_id, :id]).merge(user_id: current_user.id, evaluate_price: 0)
    end

    def set_item
      @item = Item.find(params[:id])
    end
end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  def index
  end

  def sell_list
    @items = current_user.items
  end

  def buy_list
    @items = current_user.items
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :shooting, :shooting_end]
  def edit
  end

  def update
    @user.update(user_params)
    redirect_to root_path
  end

  def show
  end

  def shooting
  end

  def shooting_end
    @user.update(clear: 1)
    redirect_to root_path
  end

  private
   def user_params
    params.require(:user).permit(:nickname, :family_name, :name, :family_name_kana, :name_kana, :postal_code, :prefecture, :city, :town, :building_name, :phone_number, :card_number, :expiration_number, :security_code)
   end

   def set_user
     @user = User.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def br(str)
    html_escape(str).gsub(/\r\n|\r|\n/, "<br />").html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/my_page_helper.rb
module MyPageHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buyers/create.html.haml
.container
  = render partial: "layouts/header_plane"
  .main
    .form
      .form__inner
        %p.form__title 購入が完了しました。
      .form__inner
        .form__inner__container
          .item_info
            = image_tag @item.images[0].image, class: "item_info__item_image"
            %p.item_info__item_name #{@item.name}
            .item_info__price_info
              %p.item_info__price_info__item_price ¥#{@item.price}
              %p.item_info__price_info__delivery_fee #{@item.delivery_fee}
      .form__inner
        .form__inner__container
          %p.buy_info__title 配送先
          .address_info
            %ul.address_info__list.buy_info__list
              %li.address_info__zip_code 〒#{current_user.zip_code.insert(3, "-")}
              %li.address_info__address  #{current_user.prefecture}#{current_user.city}#{current_user.house_number}#{current_user.building}
              %li.address_info__name     #{current_user.family_name} #{current_user.first_name}
      .form__inner
        .form__inner__container
          .payment_info
            %p.buy_info__title 支払い方法
            %ul.payment_info__list.buy_info__list
              %li.payment_info__number #{current_user.number}
              %li.address_info__expire_date  #{current_user.expire_month}/ #{current_user.expire_year}
              %li.address_info__company #{current_user.campany}
      .form__inner
        .form__inner__container
          .transaction_info
            %p.buy_info__title 発送通知後の流れ
            %ul.transaction_info__list.buy_info__list
              %li.transaction_info__list__item
                %span.evaluation_icon.icon_face--good
                  %i.icon.fa.fa-circle.fa-stack-1x.color_good
                  %i.icon.fa.fa-smile-o.fa-stack-1x.fa-inverse
                %span.evaluation_icon.icon_face--normal
                  %i.icon.fa.fa-circle.fa-stack-1x.color_normal
                  %i.icon.fa.fa-meh-o.fa-stack-1x.fa-inverse
                %span.evaluation_icon.icon_face--bad
                  %i.icon.fa.fa-circle.fa-stack-1x.color_bad
                  %i.icon.fa.fa-frown-o.fa-stack-1x.fa-inverse
              %li.transaction_info__list__item
                %p.transaction_description
                  商品を受け取ったら
                  %br/
                  出品者の評価をしましょう。
                  %br/
                  購入代金が出品者に振り込まれます。
                  %br/
                  評価後に取引は完了です。
              %li.transaction_info__list__item
                = link_to "トップページへもどる", root_path
  = render partial: "layouts/registration_footer"

app/views/buyers/new.html.haml
.container
  = render partial: "layouts/header_plane"
  .main
    .form
      .form__inner
        %p.form__title 購入を確定しますか？
      .form__inner
        .form__inner__container
          .item_info
            = image_tag @item.images[0].image, class: "item_info__item_image"
            %p.item_info__item_name #{@item.name}
            .item_info__price_info
              %p.item_info__price_info__item_price ¥ #{@item.price}
              %p.item_info__price_info__delivery_fee #{@item.delivery_fee}
            .item_info__total_info.clearfix
              %p.item_info__total_info__title 支払い金額
              %p.item_info__total_info__price ¥ #{@item.price}
            = link_to "購入する", item_buyers_path(@item), method: :post, class: "item_info__buy_btn"
      .form__inner
        .form__inner__container
          %p.buy_info__title 配送先
          .address_info
            %ul.address_info__list.buy_info__list
              %li.address_info__zip_code 〒#{current_user.zip_code.insert(3, "-")}
              %li.address_info__address  #{current_user.prefecture}#{current_user.city}#{current_user.house_number}#{current_user.building}
              %li.address_info__name     #{current_user.family_name} #{current_user.first_name}
      .form__inner
        .form__inner__container
          .payment_info
            %p.buy_info__title 支払い方法
            %ul.payment_info__list.buy_info__list
              %li.payment_info__number #{current_user.number}
              %li.address_info__expire_date  #{current_user.expire_month}/ #{current_user.expire_year}
              %li.address_info__company #{current_user.campany}
  = render partial: "layouts/registration_footer"

app/views/layouts/_footer.html.haml
%footer.general_footer
  .genaral_footer__character
  .general_footer__logo_container
    =image_tag "logos/copicari_white.png", class: "general_footer__logo" do
      =link_to root_path class: "logo"
  %p.general_footer__copy_rights ©2017 copicari
=link_to new_item_path, class: "sell_btn" do
  .sell_btn__text 出品
  %i.fa.fa-camera.sell_btn__icon

app/views/layouts/_header.html.haml
%header.general_header
  .header__inner.clearfix
    .header__inner__logo_container
      =link_to root_path, class: "logo" do
        =image_tag "logos/copicari.png", class: "header__inner__logo"
    = form_tag "/items/search", method: "GET", class: "header__inner__form" do
      %input.header__inner__form__text_field{name:"keyword", placeholder:"商品検索", type:"text"}
      %button.header__inner__form__btn{type:"submit"}
        %i.fa.fa-search
    .header__inner__links.clearfix
      %ul.header__inner__links__left
        %ul#menu
          %li
            カテゴリー
            %ul.child
              %li
                %a{:href => "#"} レディース
              %li
                %a{:href => "#"} メンズ
              %li
                %a{:href => "#"} ベビー・キッズ
              %li
                %a{:href => "#"} インテリア・住まい・小物
              %li
                %a{:href => "#"} エンタメ・ホビー
              %li
                %a{:href => "#"} コスメ・香水・美容
              %li
                %a{:href => "#"} 家電・スマホ・カメラ
              %li
                %a{:href => "#"} スポーツ・レンジャー
              %li
                %a{:href => "#"} ハンドメイド
              %li
                %a{:href => "#"} チケット
              %li
                %a{:href => "#"} 自転車・オートバイ
              %li
                %a{:href => "#"} その他

      %ul.header__inner__links__right
        - if user_signed_in?
          = link_to "マイページ", my_pages_path, class: "header__inner__links__item--blue"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__inner__links__item--red"
        -else
          = link_to "ログイン", new_user_session_path, class: "header__inner__links__item--red"
          = link_to "新規会員登録", new_user_registration_path, class: "header__inner__links__item--blue"

app/views/layouts/_header_plane.html.haml
.header__logo_container
  =link_to root_path class: "logo" do
    =image_tag "logos/copicari.png", class: "header__logo"

app/views/layouts/_image.html.haml
= f.fields_for :item_images do |pf|
  = pf.file_field :image, class: "sell_form__inner__container__image"

app/views/layouts/_items_list.html.haml
- @items.each do |item|
  .item_content
    = link_to item_path(item) do
      .item_box
        - if item.buy == 1
          = image_tag item.item_images[0].image , class: "item_box__image"
          %span.item_box__image--sold SOLD
        - else
          = image_tag item.item_images[0].image , class: "item_box__image"

        .item_box__body
          .item_box__body__name_box
            %p.item_box__body__name_box__name  #{item.name}
          %p.item_box__body__price ¥ #{item.price.to_s(:delimited)}
          %span円
          / = render partial: "layouts/like_box_for_list", locals: {item: item}
          %p.item_box__body__tax   (税 ¥0)

app/views/layouts/_my_page_menu_bar.html.haml
%ul.container__inner__menu
  %li.container__inner__menu__item.container__inner__menu__item--grey
    マイページメニュー
  %li.container__inner__menu__item
    = link_to "出品商品一覧", sell_list_my_pages_path
  %li.container__inner__menu__item
    = link_to "購入商品一覧", buy_list_my_pages_path
  %li.container__inner__menu__item
    = link_to "ユーザー情報変更", edit_user_path(current_user)

app/views/layouts/_registration_footer.html.haml
%footer
  %ul.footer__links.clearfix
    %li.footer__links__item プライバシーポリシー
    %li.footer__links__item 利用規約
    %li.footer__links__item 特定商取引に関する表記
  = image_tag "logos/copicari_logo_small.png"
  %p.footer__copy_rights ©2017 copicari

app/views/layouts/_registration_header.html.haml
.header__content.clearfix
  .header__content__logo
    =link_to root_path class: "logo" do
      =image_tag "logos/copicari.png"
  %ul.header__content__progress_bar.clearfix
    %li.header__content__progress_bar__item.stage1 会員情報
    %li.header__content__progress_bar__item.stage2 住所入力
    %li.header__content__progress_bar__item.stage3 支払い方法
    %li.header__content__progress_bar__item.stage4 完了

app/views/layouts/_small_item_list.html.haml
.container__right_inner__item_box
  .container__right_inner__item_box__title.clearfix
    %h2 #{title}
  .container__right_inner__item_box__content.clearfix
    - @items.each do |item|
      = link_to item_path(item) do
        .item_box
          = image_tag item.item_images[0].image , class: "item_box__image"
          .item_box__body
            .item_box__body__name_box
              %p.item_box__body__name_box__name  #{item.name}
              %p.item_box__body__price ¥ #{item.price.to_s(:delimited)}
              %p.item_box__body__tax (税 ¥0)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title トミカリ
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag('favicon.ico')
  %body
    = yield